### PR TITLE
Events appear in ga4

### PR DESCRIPTION
**Pull request by JanZeman**
Hello, the text below is mostly copied from our previous conversation...

At this step my goal was to see at least one event that originates from the SDK code on my "Learn GA4" Analytics property. I set up one Android and one Web stream there but today used only the Web one as I saw your appsettings.json expects exactly this one.

I removed the debug param in WeatherForecastController to use "/mp/collect" instead of "/debug/mp/collect" and hoped some event appears on my GA4. That however was not the case. I had to set up few tools to be able to observer bit more closer what is happening. Namely Charles proxy and its SSL certificate and Postman where I tried to mimic the requests.

Thank to those tools I discovered 2 problems:

timestamp_micros value was set in seconds but must be in microseconds.

1. There was a tiny typo in URL formatting that added the $ character which made the request invalid.
2. The PR fixes the above plus some other smaller typos and formatting.

I am attaching few screenshots, mainly the one from GA. The "test_event" originates from SDK.
image

The other images are from Charles proxy capturing the traffic between SDK and Analytics server.
image

image

I also touched unit tests that did not compile at the moment. I got them to green but did not make it part of this PR as I presume your plan is to extent mocks usage whereas my quick fix was 'gaOptions', i.e. these became rather integration tests communicating with "/debug/mp/collect".

My big goal would be to see the Users being captured in the Audience. This is still empty but we know that this is not in the scope of those first commits.
image

### CODE REVIEW

**Comment by LindaLawton** [comment]
I merged this looks great.  I must say its nice to have someone to do code reviews for me for a change.

Lets open up issues for anything regarding how the data gets sent.  Then we can fix each issue as we spot them.

**Comment by JanZeman** [comment]
That sounds simply great and yes, creating a separated issues will give the structured and organized process. I can see you created one already @LindaLawton. In general I probably can give only few hours a week during the evenings or weekend time, now having some vacation. I put entry to my calendar and will regularly return and contribute. Many greetings, Jan

**Comment by LindaLawton** [comment]
I have a project with my current client we are getting to release to production in a few months so my time is also limited.

**Comment by JanZeman** [comment]
Fully understood, somehow we will manage :)

**Pull request merged**
